plugins {
    id 'java'
}

group = 'com.nexusforge'
version = '0.0.1-SNAPSHOT'
description = '核心模块'


repositories {
    mavenCentral()
}

dependencies {
    implementation project(':nexus-forge-common')

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation("org.springframework.boot:spring-boot-starter-aspectj")
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation("com.bucket4j:bucket4j_jdk17-core:8.19.0")
    implementation 'com.github.ben-manes.caffeine:caffeine:3.2.4'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

test {
    useJUnitPlatform()
}