plugins {
    id 'java'
}

group = 'com.nexusforge'
version = '0.0.1-SNAPSHOT'
description = '认证模块'


repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}