plugins {
    id 'java'
}

group = 'com.nexusforge'
version = '0.0.1-SNAPSHOT'
description = '认证模块'


repositories {
    mavenCentral()
}

dependencies {

    implementation project(':nexus-forge-common')
    implementation project(':nexus-forge-user')

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui")

    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}