plugins {
    id 'java'
}

group = 'com.nexusforge'
version = '0.0.1-SNAPSHOT'
description='启动模块'

repositories {
    mavenCentral()
}

bootJar {
    enabled = true
}

dependencies {

    implementation project(':nexus-forge-core')
    implementation project(':nexus-forge-common')
    implementation project(':nexus-forge-user')
    implementation project(':nexus-forge-auth')
    implementation project(':nexus-forge-file')


    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}