plugins {
    id 'java'
}

group = 'com.nexusforge'
version = '0.0.1-SNAPSHOT'
description = '文件模块'


repositories {
    mavenCentral()
}

dependencies {

    implementation project(':nexus-forge-common')

    implementation platform('software.amazon.awssdk:bom:2.46.16')
    implementation("software.amazon.awssdk:s3")
    implementation("software.amazon.awssdk:s3-transfer-manager")
    implementation("software.amazon.awssdk:auth")
    implementation("software.amazon.awssdk:regions")

}